=== gerkone/pyTORCS-docker/vtorcs-RL-color/src/libs/tgf/params.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
                          Definitions for params files                                
    file                 : params.dtd
    created              : Fri Aug 13 22:29:02 CEST 1999
    copyright            : (C) 1999 by Eric Espie                         
    email                : torcs@free.fr   
    version              : $Id: params.dtd,v 1.3 2002/11/16 07:20:36 torcs Exp $                                  
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->


<!ELEMENT params (section)+>
<!ATTLIST params
          name CDATA #REQUIRED
	  type CDATA #REQUIRED
	  mode CDATA #IMPLIED
>

<!ELEMENT section (attnum | attstr | section)+>
<!ATTLIST section
          name CDATA #REQUIRED
>

<!ELEMENT attnum EMPTY>
<!ATTLIST attnum 
          name CDATA #REQUIRED
	  min  CDATA #IMPLIED
	  max  CDATA #IMPLIED
	  unit CDATA #IMPLIED
          val  CDATA #REQUIRED
>

<!ELEMENT attstr EMPTY>
<!ATTLIST attstr 
          name CDATA #REQUIRED
	  in   CDATA #IMPLIED
          val  CDATA #REQUIRED
>

=== gerkone/pyTORCS-docker/torcs/data/tracks/oval/d-speedway/d-speedway.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    file                 : d-speedway.xml
    created              : Sun Mar 19 00:13:46 CET 2000
    copyright            : (C) 2000 by Eric Espie                         
    email                : torcs@free.fr   
    version              : $Id: d-speedway.xml,v 1.2 2004/02/09 05:42:43 torcs Exp $                                  
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!DOCTYPE params SYSTEM "../../../../src/libs/tgf/params.dtd" [
<!-- general definitions for tracks -->
<!ENTITY default-surfaces SYSTEM "../../../data/tracks/surfaces.xml">
<!ENTITY default-objects SYSTEM "../../../data/tracks/objects.xml">
]>

<params name="D-Speedway" type="trackdef" mode="mw">


  <!-- Surfaces -->
  <section name="Surfaces">
      &default-surfaces;
  </section>

  <!-- Objects -->
  <section name="Objects">
      &default-objects;
  </section>  <!-- Objects -->

  <section name="Header">
    <attstr name="name"        val="D-Speedway"/>
    <attstr name="category"    val="oval"/>
    <attnum name="version"     val="4"/>
    <attstr name="author"      val="E.Espie"/>
    <attstr name="description" val="D shaped SpeedWay"/>
  </section>

  <section name="Graphic">
    <attstr name="3d description" val="d-speedway.ac"/>

    <attstr name="background image" val="background.png"/>
    <attnum name="background type" val="4"/>

    <attnum name="background color R" val="0.5"/>
    <attnum name="background color G" val="0.5"/>
    <attnum name="background color B" val="0.55"/>

    <attnum name="ambient color R" val="0.1"/>
    <attnum name="ambient color G" val="0.1"/>
    <attnum name="ambient color B" val="0.05"/>

    <attnum name="diffuse color R" val="1"/>
    <attnum name="diffuse color G" val="1"/>
    <attnum name="diffuse color B" val="1"/>

    <attnum name="specular color R" val="0.1"/>
    <attnum name="specular color G" val="0.1"/>
    <attnum name="specular color B" val="0.1"/>


    <attnum name="light position x" val="-0"/>
    <attnum name="light position y" val="1000"/>
    <attnum name="light position z" val="300"/>

    <section name="Environment Mapping">
      <section name="1">
	<attstr name="env map image" val="env.png"/>
      </section>
    </section>

    <section name="Terrain Generation">
      <attnum name="track step" unit="m" val="20"/>
      <attnum name="border margin" unit="m" val="300"/>
      <attnum name="border step" unit="m" val="50"/>
      <attnum name="border height" unit="m" val="20"/>
      <attstr name="surface" val="grass6"/>
      <attstr name="relief file" val="d-speedway-relief.ac"/>
    </section>

  </section>


  <section name="Main Track">

    <attnum name="width" unit="m" val="30.0"/>
    <attnum name="profil steps length" unit="m" val="10"/>

    <!-- PITS -->
    <section name="Pits">
      <attstr name="type" val="track side"/>
      <attstr name="side" val="left"/>
      <attstr name="entry" val="pit entry"/>
      <attstr name="start" val="last seg"/>
      <attstr name="end" val="start lane"/>
      <attstr name="exit" val="pit exit"/>
      <attnum name="length" unit="m" val="15"/>
      <attnum name="width" unit="m" val="6"/>
    </section>  <!-- PITS -->

    <section name="Track Segments">

      <section name="start lane">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="150"/>
	<attstr name="surface" val="concrete4"/>
	<attnum name="banking start" unit="deg" val="-15"/>
	<attnum name="banking end" unit="deg" val="-15"/>

	<section name="Right Barrier">
	  <attstr name="surface" val="wall"/>
	  <attstr name="style" val="wall"/>
	  <attnum name="width" val="0.5"/>
	  <attnum name="height" val="1.5"/>	  
	</section>

	<section name="Left Border">
	  <attstr name="surface" val="b-concrete4-concrete-l1"/>
	  <attnum name="width" val="1.0"/>
	  <attstr name="style" val="plan"/>
	</section>

	<section name="Left Side">
	  <attnum name="start width" val="15"/>
	  <attnum name="end width" val="15"/>
	  <attstr name="surface" val="concrete-pits"/>
	  <attstr name="type" in="level,tangent" val="level"/>
	</section>
      </section>

      <section name="pit exit">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="150"/>

 	<section name="Left Border">
	  <attstr name="surface" val="b-concrete4-concrete-l1p"/>
	  <attnum name="width" val="1.0"/>
	  <attstr name="style" val="plan"/>
	</section>

	<section name="Left Side">
	  <attstr name="surface" val="concrete"/>
	  <attnum name="end width" val="8"/>
	</section>
      </section>

      <!-- TURN 1 -->
      <section name="turn1-1">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="400"/>
	<attnum name="arc" unit="deg" val="30"/>

 	<section name="Left Border">
	  <attstr name="surface" val="b-concrete4-concrete-l1"/>
	  <attnum name="width" val="1.0"/>
	  <attstr name="style" val="plan"/>
	</section>
      </section>

      <section name="turn1-2">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="300"/>
	<attnum name="arc" unit="deg" val="60"/>
      </section>

      <section name="turn1-3">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="400"/>
	<attnum name="arc" unit="deg" val="60"/>
      </section>

      <!-- TURN 2 -->
      <section name="turn2-1">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="900"/>
	<attnum name="arc" unit="deg" val="60"/>
     </section>

      <!-- TURN 3 -->
      <section name="turn3-1">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="400"/>
	<attnum name="arc" unit="deg" val="60"/>
      </section>

      <section name="turn3-2">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="300"/>
	<attnum name="arc" unit="deg" val="60"/>
      </section>

      <section name="turn3-3">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="400"/>
	<attnum name="arc" unit="deg" val="30"/>
      </section>

      <section name="pit entry">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="150"/>

 	<section name="Left Border">
	  <attstr name="surface" val="b-concrete4-concrete-l1p"/>
	  <attnum name="width" val="1.0"/>
	  <attstr name="style" val="plan"/>
	</section>

	<section name="Left Side">
	  <attstr name="surface" val="concrete"/>
	  <attnum name="end width" val="15"/>
	</section>
      </section>


      <section name="last seg">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="150"/>

	<section name="Left Border">
	  <attstr name="surface" val="b-concrete4-concrete-l1"/>
	  <attnum name="width" val="1.0"/>
	  <attstr name="style" val="plan"/>
	</section>

	<section name="Left Side">
	  <attnum name="end width" val="15"/>
	  <attstr name="surface" val="concrete-pits"/>
	  <attstr name="type" in="level,tangent" val="level"/>
	</section>
      </section>


    </section>
  </section>

  <!-- Cameras -->
  <section name="Cameras">

    <section name="cam 0">
      <!-- Camera's position relative to a segment -->
      <attstr name="segment"  val="start lane"/>
      <attnum name="to right" val="0"/>
      <attnum name="to start" val="100"/>
      <attnum name="height"   val="4"/>
      <!-- Camera field of view, indicates the first and last segment viewed -->
      <attstr name="fov start" val="start lane"/> <!-- included  -->
      <attstr name="fov end"   val="turn1-1"/> <!-- excluded -->
    </section>

    <section name="cam 1">
      <!-- Camera's position relative to a segment -->
      <attstr name="segment"  val="turn1-2"/>
      <attnum name="to right" val="40"/>
      <attnum name="to start" unit="deg" val="30"/>
      <attnum name="height"   val="2"/>
      <!-- Camera field of view, indicates the first and last segment viewed -->
      <attstr name="fov start" val="turn1-1"/> <!-- included  -->
      <attstr name="fov end"   val="line2-1"/> <!-- excluded -->
    </section>

    <section name="cam 4">
      <!-- Camera's position relative to a segment -->
      <attstr name="segment"  val="turn2-1"/>
      <attnum name="to right" val="40"/>
      <attnum name="to start" unit="deg" val="30"/>
      <attnum name="height"   val="2"/>
      <!-- Camera field of view, indicates the first and last segment viewed -->
      <attstr name="fov start" val="turn2-1"/> <!-- included  -->
      <attstr name="fov end"   val="turn3-1"/> <!-- excluded -->
    </section>

    <section name="cam 7">
      <!-- Camera's position relative to a segment -->
      <attstr name="segment"  val="turn3-2"/>
      <attnum name="to right" val="40"/>
      <attnum name="to start" unit="deg" val="30"/>
      <attnum name="height"   val="2"/>
      <!-- Camera field of view, indicates the first and last segment viewed -->
      <attstr name="fov start" val="turn3-1"/> <!-- included  -->
      <attstr name="fov end"   val="pit entry"/> <!-- excluded -->
    </section>

    <section name="cam 8">
      <!-- Camera's position relative to a segment -->
      <attstr name="segment"  val="last seg"/>
      <attnum name="to right" val="0"/>
      <attnum name="to start" val="100"/>
      <attnum name="height"   val="4"/>
      <!-- Camera field of view, indicates the first and last segment viewed -->
      <attstr name="fov start" val="pit entry"/> <!-- included  -->
      <attstr name="fov end"   val="start lane"/> <!-- excluded -->
    </section>

  </section>


</params>

=== gerkone/pyTORCS-docker/vtorcs-RL-color/exp-settings/results/quickrace/results-2012-06-18-19-18.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE params SYSTEM "/home/giuse/torcs-1.3.1/BUILD/share/games/torcs/config/params.dtd">
<?xml-stylesheet type="text/xsl" href="file:////home/giuse/torcs-1.3.1/BUILD/share/games/torcs/config/style.xsl"?>

<params name="Results">
  <section name="Header">
    <attnum name="date" val="1.34004e+09"/>
  </section>

  <section name="Current">
    <attnum name="current track" val="1"/>
    <attnum name="current race" val="1"/>
    <attnum name="current driver" val="1"/>
  </section>

  <section name="Street 1">
    <section name="Drivers">
      <section name="1">
        <attstr name="dll name" val="human"/>
        <attnum name="index" val="1"/>
      </section>

    </section>

    <section name="Results">
      <section name="Quick Race">
        <attnum name="laps" val="0"/>
        <section name="Rank">
          <section name="1">
            <attstr name="name" val="Player"/>
            <attstr name="car" val="car7-trb1"/>
            <attnum name="index" val="0"/>
            <attnum name="laps" val="0"/>
            <attnum name="time" val="0"/>
            <attnum name="best lap time" val="0"/>
            <attnum name="top speed" val="55.56"/>
            <attnum name="dammages" val="10087"/>
            <attnum name="pits stops" val="0"/>
            <attstr name="module" val="human"/>
            <attnum name="idx" val="1"/>
            <attnum name="points" val="0"/>
          </section>

        </section>

      </section>

    </section>

  </section>

  <section name="Standings">
    <section name="1">
      <attstr name="name" val="Player"/>
      <attstr name="module" val="human"/>
      <attnum name="idx" val="1"/>
      <attnum name="points" val="0"/>
    </section>

  </section>

</params>

=== gerkone/pyTORCS-docker/vtorcs/data/tracks/a-speedway/a-speedway.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    file                 : a-speedway.xml
    created              : Sun Mar 19 00:13:46 CET 2000
    copyright            : (C) 2000 by Eric Espie                         
    email                : torcs@free.fr   
    version              : $Id: a-speedway.xml,v 1.9.2.1 2008/08/19 21:06:00 berniw Exp $                                  
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!DOCTYPE params SYSTEM "../../../src/libs/tgf/params.dtd" [
<!-- general definitions for tracks -->
<!ENTITY default-surfaces SYSTEM "../../../data/tracks/surfaces.xml">
]>

<params name="A-Speedway" type="trackdef" mode="mw">

  <section name="Surfaces">
    <section name="List">
      &default-surfaces;
    </section>
  </section>

  <section name="Header">
    <attstr name="name"        val="A-Speedway"/>
    <attstr name="category"    val="oval"/>
    <attnum name="version"     val="3"/>
    <attstr name="author"      val="E. Espie"/>
    <attstr name="description" val="Rectangle shaped Speedway"/>
  </section>

  <section name="Graphic">
    <attstr name="3d description" val="a-speedway.ac"/>

    <attstr name="background image" val="background.png"/>
    <attnum name="background color R" val="0.59375"/>
    <attnum name="background color G" val="0.75"/>
    <attnum name="background color B" val="0.96875"/>

    <attnum name="ambient color R" val="0.1"/>
    <attnum name="ambient color G" val="0.1"/>
    <attnum name="ambient color B" val="0.05"/>

    <attnum name="diffuse color R" val="1"/>
    <attnum name="diffuse color G" val="1"/>
    <attnum name="diffuse color B" val="1"/>

    <attnum name="specular color R" val="0.1"/>
    <attnum name="specular color G" val="0.1"/>
    <attnum name="specular color B" val="0.1"/>


    <attnum name="light position x" val="-0"/>
    <attnum name="light position y" val="1000"/>
    <attnum name="light position z" val="300"/>

    <section name="Terrain Generation">
      <attnum name="track step" unit="m" val="30"/>
      <attnum name="border margin" unit="m" val="100"/>
      <attnum name="border step" unit="m" val="30"/>
      <attnum name="border height" unit="m" val="0"/>
      <attstr name="orientation" val="counter-clockwise"/>
      <attstr name="relief file" val="a-speedway-relief.ac"/>
    </section>
  </section>


  <section name="Main Track">

    <attstr name="surface" in="asphalt,grass,sand" val="asphalt-lines"/>
    <attnum name="width" unit="m" val="25.0"/>
    <attnum name="steps length" val="5" unit="m"/>

    <attstr name="rside surface"  val="concrete"/>
    <attnum name="rside width"    val="3.0"/>
    <attstr name="rside type" in="tangent,level" val="tangent"/>

    <attstr name="lside surface"  val="asphalt-pits"/>
    <attnum name="lside width"    val="15.0"/>
    <attstr name="lside type" in="tangent,level" val="level"/>

    <attnum name="profil steps length" val="8" unit="m"/>

    <attstr name="pit type"   val="track side"/>
    <attstr name="pit entry"  val="segment s1"/>
    <attstr name="pit start"  val="last segment"/>
    <attstr name="pit end"    val="start lane"/>
    <attstr name="pit exit"   val="segment e2"/>
    <attstr name="pit side"   val="left"/>
    <attnum name="pit length" val="15" unit="m"/>
    <attnum name="pit width"  val="5" unit="m"/>

    <section name="segments">

      <section name="start lane">
	<attnum name="z start" val="0" unit="m"/>
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="150"/>
	<attnum name="banking start" val="-5" unit="deg"/>
	<attnum name="banking end" val="-5" unit="deg"/>
 	<attnum name="z end" val="0" unit="m"/>
	<attnum name="profil start tangent" val="0" unit="%"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="segment e2">
	<attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="100"/>
	<attstr name="lside surface" val="asphalt"/>
	<attnum name="lside end width" val="6"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="turn 1">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="90"/>
	<attstr name="lside surface" val="concrete"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="segment l1">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="140"/>
	<attnum name="banking end" val="-10" unit="deg"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="turn 2">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="90"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="opposite straight 1">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="250"/>
	<attnum name="banking end" val="-5" unit="deg"/>
 	<attnum name="z end" val="-1.089446784" unit="m"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
     </section>


      <section name="opposite straight 2">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="250"/>
	<attnum name="banking end" val="-10" unit="deg"/>
 	<attnum name="z end" val="0" unit="m"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
    </section>

      <section name="turn 3">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="90"/>
	<attnum name="banking end" val="-10" unit="deg"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="segment l3">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="140"/>
	<attnum name="banking end" val="-5" unit="deg"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="turn 4">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="90"/>
	<attnum name="banking end" val="-5" unit="deg"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="segment s1">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="100"/>
	<attnum name="lside end width" val="15"/>
	<attstr name="lside surface" val="asphalt"/>
	<attnum name="banking end" val="-5" unit="deg"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

      <section name="last segment">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="150"/>
	<attstr name="lside surface" val="asphalt-pits"/>
	<attnum name="banking end" val="-5" unit="deg"/>
 	<attnum name="z end" val="0" unit="m"/>
	<attnum name="profil end tangent" val="0" unit="%"/>
      </section>

    </section>

  </section>


  <section name="Cameras">

    <section name="list">

      <section name="startcam">
	<!-- Camera's position relative to a segment -->
	<attstr name="segment"   val="start lane"/>
	<attnum name="to right"  val="10.0"/>
	<attnum name="to start"  val="250"/>
	<attnum name="height"    val="30"/>
	<!-- Camera field of view, indicates the first and last segment viewed -->
	<attstr name="fov start" val="segment s2"/>
	<attstr name="fov end"   val="segment e2"/>	
      </section>

      <section name="t1cam">
	<attstr name="segment"   val="start lane"/>
	<attnum name="to right"  val="-25.0"/>
	<attnum name="to start"  val="50" unit="deg"/>
	<attnum name="height"    val="30"/>
	<attstr name="fov start" val="segment e2"/>
	<attstr name="fov end"   val="segment l1"/>
      </section>

      <section name="t2cam">
	<attstr name="segment"   val="turn 2"/>
	<attnum name="to right"  val="45.0"/>
	<attnum name="to start"  val="45" unit="deg"/>
	<attnum name="height"    val="15"/>
	<attstr name="fov start" val="segment l1"/>
	<attstr name="fov end"   val="opposite straight 2"/>
      </section>

      <section name="t3cam">
	<attstr name="segment"   val="turn 3"/>
	<attnum name="to right"  val="-25.0"/>
	<attnum name="to start"  val="0" unit="deg"/>
	<attnum name="height"    val="20"/>
	<attstr name="fov start" val="opposite straight 2"/>
	<attstr name="fov end"   val="segment l3"/>
      </section>

      <section name="t4cam">
	<attstr name="segment"   val="turn 4"/>
	<attnum name="to right"  val="45.0"/>
	<attnum name="to start"  val="65" unit="deg"/>
	<attnum name="height"    val="20"/>
	<attstr name="fov start" val="segment l3"/>
	<attstr name="fov end"   val="segment s2"/>
      </section>
    </section>

  </section>

</params>

=== gerkone/pyTORCS-docker/vtorcs/config/raceman/champ.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	 file        : champ.xml
	 created     : Sat Jan 25 08:58:03 CET 2003
	 copyright   : (C) 2003 by Eric Espiï¿½                         
	 email       : Eric.Espie@torcs.org   
	 version     : $Id: champ.xml,v 1.8.2.2 2008/08/05 22:46:12 berniw Exp $                                  
	 -->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!DOCTYPE params SYSTEM "../libs/tgf/params.dtd">

<params name="Championship" type="param" mode="mw">
	
	<section name="Header">
		<attstr name="name" val="Championship"/>
		<attstr name="description" val="Championship"/>
		<attnum name="priority" val="30"/>
		<attstr name="menu image" val="data/img/splash-dtm.png"/>
		<attstr name="run image" val="data/img/splash-run-practice.png"/>
		<attstr name="start image" val="data/img/splash-dtm.png"/>
	</section>
	
	<section name="Tracks">
		<attnum name="maximum number" val="20"/>
		
		<section name="1">
			<attstr name="name" val="g-track-1"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="2">
			<attstr name="name" val="e-track-6"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="3">
			<attstr name="name" val="g-track-3"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="4">
			<attstr name="name" val="street-1"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="5">
			<attstr name="name" val="wheel-2"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="6">
			<attstr name="name" val="ruudskogen"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="7">
			<attstr name="name" val="aalborg"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="8">
			<attstr name="name" val="alpine-1"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="9">
			<attstr name="name" val="dirt-3"/>
			<attstr name="category" val="dirt"/>
		</section>
		<section name="10">
			<attstr name="name" val="michigan"/>
			<attstr name="category" val="oval"/>
		</section>
		<section name="11">
			<attstr name="name" val="forza"/>
			<attstr name="category" val="road"/>
		</section>
		<section name="12">
			<attstr name="name" val="alpine-2"/>
			<attstr name="category" val="road"/>
		</section>		
	</section>
	
	<section name="Races">		
		<section name="1">
			<attstr name="name" val="Qualifications"/>
		</section>
		
		<section name="2">
			<attstr name="name" val="Race"/>
		</section>
	</section>
	
	<section name="Qualifications">
		<attnum name="laps" val="3"/>
		<attstr name="type" val="qualifications"/>
		<attstr name="starting order" val="drivers list"/>
		<attstr name="display mode" val="results only"/>
		<attstr name="restart" val="no"/>
		<attstr name="display results" val="yes"/>
		<attstr name="must complete" val="yes"/>
		
		<section name="Starting Grid">
			<attnum name="rows" val="1.000000"/>
			<attnum name="distance to start" val="100.000000"/>
			<attnum name="distance between columns" val="20.000000"/>
			<attnum name="offset within a column" val="10.000000"/>
			<attnum name="initial speed" val="0.000000"/>
			<attnum name="initial height" val="0.200000"/>
		</section>		
	</section>
	
	<section name="Race">
		<attnum name="distance" unit="km" val="180"/>
		<attstr name="type" val="race"/>
		<attstr name="starting order" val="last race"/>
		<attstr name="restart" val="no"/>
		<attnum name="maximum drivers" val="40"/>
		<attstr name="splash menu" val="yes"/>
		
		<section name="Starting Grid">
			<attnum name="rows" val="2.000000"/>
			<attnum name="distance to start" val="25.000000"/>
			<attnum name="distance between columns" val="30.000000"/>
			<attnum name="offset within a column" val="10.000000"/>
			<attnum name="initial speed" val="0.000000"/>
			<attnum name="initial height" val="0.200000"/>
		</section>
		
		<section name="Points">
			<section name="1">
				<attnum name="points" val="10"/>
			</section>
			<section name="2">
				<attnum name="points" val="8"/>
			</section>
			<section name="3">
				<attnum name="points" val="6"/>
			</section>
			<section name="4">
				<attnum name="points" val="5"/>
			</section>
			<section name="5">
				<attnum name="points" val="4"/>
			</section>
			<section name="6">
				<attnum name="points" val="3"/>
			</section>
			<section name="7">
				<attnum name="points" val="2"/>
			</section>
			<section name="8">
				<attnum name="points" val="1"/>
			</section>
		</section>
	</section>	
	
	<section name="Drivers">
		<attnum name="maximum number" val="50"/>
		<attstr name="focused module" val="inferno"/>
		<attnum name="focused idx" val="7.000000"/>
		
		<section name="1">
			<attnum name="idx" val="6"/>
			<attstr name="module" val="berniw"/>
		</section>
		
		<section name="2">
			<attnum name="idx" val="6"/>
			<attstr name="module" val="olethros"/>
		</section>
		
		<section name="3">
			<attnum name="idx" val="8"/>
			<attstr name="module" val="lliaw"/>
		</section>
		
		<section name="4">
			<attnum name="idx" val="9"/>
			<attstr name="module" val="tita"/>
		</section>
		
		<section name="5">
			<attnum name="idx" val="3"/>
			<attstr name="module" val="inferno"/>
		</section>
		
		<section name="6">
			<attnum name="idx" val="7"/>
			<attstr name="module" val="damned"/>
		</section>
		
		<section name="7">
			<attnum name="idx" val="4"/>
			<attstr name="module" val="bt"/>
		</section>
		
		<section name="8">
			<attnum name="idx" val="7"/>
			<attstr name="module" val="berniw2"/>
		</section>

		<section name="9">
			<attnum name="idx" val="4"/>
			<attstr name="module" val="lliaw"/>
		</section>
		
		<section name="10">
			<attnum name="idx" val="1"/>
			<attstr name="module" val="human"/>
		</section>
		
	</section>
	
	<section name="Configuration">
		
		<section name="1">
			<attstr name="type" val="drivers select"/>
		</section>
	</section>
	
</params>
