=== gerkone/pyTORCS-docker/vtorcs-RL-color/src/libs/tgf/params.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
                          Definitions for params files                                
    file                 : params.dtd
    created              : Fri Aug 13 22:29:02 CEST 1999
    copyright            : (C) 1999 by Eric Espie                         
    email                : torcs@free.fr   
    version              : $Id: params.dtd,v 1.3 2002/11/16 07:20:36 torcs Exp $                                  
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->


<!ELEMENT params (section)+>
<!ATTLIST params
          name CDATA #REQUIRED
	  type CDATA #REQUIRED
	  mode CDATA #IMPLIED
>

<!ELEMENT section (attnum | attstr | section)+>
<!ATTLIST section
          name CDATA #REQUIRED
>

<!ELEMENT attnum EMPTY>
<!ATTLIST attnum 
          name CDATA #REQUIRED
	  min  CDATA #IMPLIED
	  max  CDATA #IMPLIED
	  unit CDATA #IMPLIED
          val  CDATA #REQUIRED
>

<!ELEMENT attstr EMPTY>
<!ATTLIST attstr 
          name CDATA #REQUIRED
	  in   CDATA #IMPLIED
          val  CDATA #REQUIRED
>

=== gerkone/pyTORCS-docker/torcs/src/drivers/berniw3/berniw3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    file                 : berniw3.xml
    created              : Mon Jan 19 19:28:00 CET 2004
    copyright            : (C) 2004 by Bernhard Wymann
    email                : berniw@bluewin.ch
    version              : $Id: berniw3.xml,v 1.1 2004/01/20 13:45:23 berniw Exp $
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!DOCTYPE params SYSTEM "../../libs/tgf/params.dtd">

<params name="berniw3" type="robotdef">
  <section name="Robots">
    <section name="index">

	  <section name="1">
		<!-- Driver's name (short please) -->
		<attstr name="name" val="berniw hist 1"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 1"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-dino"/>
		<attnum name="race number" val="480"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="2">
		<attstr name="name" val="berniw hist 2"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 2"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-coda"/>
		<attnum name="race number" val="481"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="3">
		<attstr name="name" val="berniw hist 3"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 3"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-gt40"/>
		<attnum name="race number" val="482"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="4">
		<attstr name="name" val="berniw hist 4"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 4"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-alfatz2"/>
		<attnum name="race number" val="483"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="5">
		<attstr name="name" val="berniw hist 5"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 5"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-a110"/>
		<attnum name="race number" val="484"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="6">
		<attstr name="name" val="berniw hist 6"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 6"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-corvette-ttop"/>
		<attnum name="race number" val="485"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="7">
		<attstr name="name" val="berniw hist 7"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 7"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-daytona"/>
		<attnum name="race number" val="486"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="8">
		<attstr name="name" val="berniw hist 8"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 8"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-db4z"/>
		<attnum name="race number" val="487"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="9">
		<attstr name="name" val="berniw hist 9"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 9"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-p4"/>
		<attnum name="race number" val="488"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="10">
		<attstr name="name" val="berniw hist 10"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's first Bot 10"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="kc-5300gt"/>
		<attnum name="race number" val="489"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	</section>
  </section>
</params>

=== gerkone/pyTORCS-docker/vtorcs-RL-color/src/drivers/berniw2/berniw2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    file                 : berniw.xml
    created              : Mon Apr 17 13:51:00 CET 2000
    copyright            : (C) 2000 by Bernhard Wymann
    email                : berniw@bluewin.ch
    version              : $Id: berniw2.xml,v 1.5.2.1 2008/05/25 21:56:11 berniw Exp $
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!DOCTYPE params SYSTEM "../../libs/tgf/params.dtd">

<params name="berniw" type="robotdef">
  <section name="Robots">
    <section name="index">

	  <section name="1">
		<!-- Driver's name (short please) -->
		<attstr name="name" val="berniw two 1"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 1"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="pw-focuswrc"/>
		<attnum name="race number" val="148"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="2">
		<attstr name="name" val="berniw two 2"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 2"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="pw-206wrc"/>
		<attnum name="race number" val="149"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="3">
		<attstr name="name" val="berniw two 3"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 3"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="pw-306wrc"/>
		<attnum name="race number" val="150"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="4">
		<attstr name="name" val="berniw two 4"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 4"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="pw-evoviwrc"/>
		<attnum name="race number" val="151"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="5">
		<attstr name="name" val="berniw two 5"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 5"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="pw-imprezawrc"/>
		<attnum name="race number" val="152"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="6">
		<attstr name="name" val="berniw two 6"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 6"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="pw-corollawrc"/>
		<attnum name="race number" val="153"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="7">
		<attstr name="name" val="berniw two 7"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 7"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="car5-trb1"/>
		<attnum name="race number" val="154"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="8">
		<attstr name="name" val="berniw two 8"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 8"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="car4-trb1"/>
		<attnum name="race number" val="155"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="9">
		<attstr name="name" val="berniw two 9"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 9"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="car7-trb1"/>
		<attnum name="race number" val="156"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	  <section name="10">
		<attstr name="name" val="berniw two 10"/>
		<attstr name="team" val="berniw"/>
		<attstr name="desc" val="Berni's second Bot 10"/>
		<attstr name="author" val="Bernhard Wymann"/>
		<attstr name="car name" val="car1-trb3"/>
		<attnum name="race number" val="157"/>
		<attnum name="red" val="0.0"/>
		<attnum name="green" val="1.0"/>
		<attnum name="blue" val="1.0"/>
      </section>

	</section>
  </section>
</params>

=== gerkone/pyTORCS-docker/vtorcs/src/raceman/dtmrace.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	 file        : dtmrace.xml
	 created     : Fri Jan  3 13:19:48 CET 2003
	 copyright   : (C) 2003 by Eric Espiï¿½                         
	 email       : Eric.Espie@torcs.org   
	 version     : $Id: dtmrace.xml,v 1.9.2.1 2008/08/05 23:47:46 berniw Exp $                                  
	 -->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!DOCTYPE params SYSTEM "../libs/tgf/params.dtd">

<params name="dtm race" type="param" mode="mw">
	
	<section name="Header">
		<attstr name="name" val="Challenge Race"/>
		<attstr name="description" val="Multiple races"/>
		<attnum name="priority" val="50"/>
		<attstr name="menu image" val="data/img/splash-dtm.png"/>
		<attstr name="run image" val="data/img/splash-run-practice.png"/>
		<attstr name="start image" val="data/img/splash-dtmstart.png"/>
	</section>
	
	<section name="Tracks">
		<attnum name="maximum number" val="1"/>
		
		<section name="1">
			<attstr name="name" val="e-track-6"/>
			<attstr name="category" val="road"/>
		</section>
	</section>
	
	<section name="Races">
		
		<section name="1">
			<attstr name="name" val="Qualifications"/>
		</section>
		
		<section name="2">
			<attstr name="name" val="Sprint Race"/>
		</section>
		
		<section name="3">
			<attstr name="name" val="Main Race"/>
		</section>
	</section>
	
	<section name="Qualifications">
		<attnum name="laps" val="3"/>
		<attstr name="type" val="qualifications"/>
		<attstr name="starting order" val="drivers list"/>
		<attstr name="display mode" val="results only"/>
		<attstr name="restart" val="no"/>
		<attstr name="display results" val="yes"/>
		<attstr name="must complete" val="yes"/>
		
		<section name="Starting Grid">
			<attnum name="rows" val="1.000000"/>
			<attnum name="distance to start" val="100.000000"/>
			<attnum name="distance between columns" val="20.000000"/>
			<attnum name="offset within a column" val="10.000000"/>
			<attnum name="initial speed" val="0.000000"/>
			<attnum name="initial height" val="0.200000"/>
		</section>
	</section>
	
	<section name="Sprint Race">
		<attnum name="distance" val="50" unit="km"/>
		<attstr name="type" val="race"/>
		<attstr name="starting order" val="last race"/>
		<attstr name="restart" val="no"/>
		<attnum name="maximum drivers" val="40"/>
		<attstr name="splash menu" val="yes"/>
		
		<section name="Starting Grid">
			<attnum name="rows" val="2.000000"/>
			<attnum name="distance to start" val="25.000000"/>
			<attnum name="distance between columns" val="20.000000"/>
			<attnum name="offset within a column" val="10.000000"/>
			<attnum name="initial speed" val="0.000000"/>
			<attnum name="initial height" val="0.200000"/>
		</section>
		
		<section name="Points">
			<section name="1">
				<attnum name="points" val="10"/>
			</section>
			<section name="2">
				<attnum name="points" val="8"/>
			</section>
			<section name="3">
				<attnum name="points" val="6"/>
			</section>
			<section name="4">
				<attnum name="points" val="5"/>
			</section>
			<section name="5">
				<attnum name="points" val="4"/>
			</section>
			<section name="6">
				<attnum name="points" val="3"/>
			</section>
			<section name="7">
				<attnum name="points" val="2"/>
			</section>
			<section name="8">
				<attnum name="points" val="1"/>
			</section>
		</section>
		
	</section>
	
	<section name="Main Race">
		<attnum name="distance" val="180" unit="km"/>
		<attstr name="type" val="race"/>
		<attstr name="starting order" val="last race"/>
		<attstr name="restart" val="no"/>
		<attstr name="splash menu" val="yes"/>
		
		<section name="Starting Grid">
			<attnum name="rows" val="2.000000"/>
			<attnum name="distance to start" val="25.000000"/>
			<attnum name="distance between columns" val="20.000000"/>
			<attnum name="offset within a column" val="10.000000"/>
			<attnum name="initial speed" val="0.000000"/>
			<attnum name="initial height" val="0.200000"/>
		</section>
		
		<section name="Points">
			<section name="1">
				<attnum name="points" val="20"/>
			</section>
			<section name="2">
				<attnum name="points" val="16"/>
			</section>
			<section name="3">
				<attnum name="points" val="12"/>
			</section>
			<section name="4">
				<attnum name="points" val="10"/>
			</section>
			<section name="5">
				<attnum name="points" val="8"/>
			</section>
			<section name="6">
				<attnum name="points" val="6"/>
			</section>
			<section name="7">
				<attnum name="points" val="4"/>
			</section>
			<section name="8">
				<attnum name="points" val="2"/>
			</section>
		</section>
	</section>
	
	<section name="Drivers">
		<attnum name="maximum number" val="50"/>
		<attstr name="focused module" val="human"/>
		<attnum name="focused idx" val="5.000000"/>
		
		<section name="1">
			<attnum name="idx" val="7"/>
			<attstr name="module" val="berniw"/>
		</section>
		
		<section name="2">
			<attnum name="idx" val="7"/>
			<attstr name="module" val="olethros"/>
		</section>
		
		<section name="3">
			<attnum name="idx" val="9"/>
			<attstr name="module" val="lliaw"/>
		</section>
		
		<section name="4">
			<attnum name="idx" val="3"/>
			<attstr name="module" val="tita"/>
		</section>
		
		<section name="5">
			<attnum name="idx" val="4"/>
			<attstr name="module" val="inferno"/>
		</section>
		
		<section name="6">
			<attnum name="idx" val="8"/>
			<attstr name="module" val="damned"/>
		</section>
		
		<section name="7">
			<attnum name="idx" val="5"/>
			<attstr name="module" val="bt"/>
		</section>
		
		<section name="8">
			<attnum name="idx" val="1.000000"/>
			<attstr name="module" val="human"/>
		</section>
		
	</section>
	
	<section name="Configuration">
		
		<section name="1">
			<attstr name="type" val="track select"/>
		</section>
		
		<section name="2">
			<attstr name="type" val="drivers select"/>
		</section>
	</section>
	
</params>

=== gerkone/pyTORCS-docker/vtorcs/src/drivers/damned/4/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    file                 : SWRC62.xml
    created              : Sat Mar 18 23:03:59 CET 2000
    copyright            : (C) 2000 by Eric Espie                         
    email                : torcs@free.fr   
    version              : $Id: default.xml,v 1.1.2.1 2008/05/28 21:34:47 berniw Exp $                                  
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!--    3D MODEL copyright (C) Patrick Wisselo  Patwo Design Production 1999 (see readme.txt) -->

<!DOCTYPE params SYSTEM "../../../../src/libs/tgf/params.dtd">

<params name="SWRC62" type="template">

	<section name="Car">
		<attnum name="initial fuel" min="1.0" max="53" unit="l" val="53.0"/>
	</section>
	
	<section name="Front Wing">
		<attnum name="angle" min="0" max="30" unit="deg" val="5"/>
	</section>
	
	<section name="Rear Wing">
		<attnum name="angle" min="0" max="30" unit="deg" val="15"/>
	</section>
	
	<section name="Gearbox">
		<section name="gears">
			<section name="r">
				<attnum name="ratio" min="-5" max="0" val="-2.96"/>
			</section>
			<section name="1">
				<attnum name="ratio" min="0" max="10" val="2.232"/>
			</section>
			<section name="2">
				<attnum name="ratio" min="0" max="10" val="1.625"/>
			</section>
			<section name="3">
				<attnum name="ratio" min="0" max="10" val="1.086"/>
			</section>
			<section name="4">
				<attnum name="ratio" min="0" max="10" val=".856"/>
			</section>
			<section name="5">
				<attnum name="ratio" min="0" max="10" val=".69"/>
			</section>
			<section name="6">
				<attnum name="ratio" min="0" max="10" val="0.6"/>
			</section>
		</section>
	</section>
		
	<section name="Brake System">
		<attnum name="front-rear brake repartition" min="0.0" max="1.0" val="0.68"/>
		<attnum name="max pressure" min="100" max="1500000" unit="kPa" val="23000"/>
	</section>
		
	<section name="Front Differential">
		<!-- type of differential : SPOOL (locked), FREE, LIMITED SLIP -->
		<attstr name="type" in="NONE,SPOOL,FREE,LIMITED SLIP" val="FREE"/>
	</section>
	
	<section name="Rear Differential">
		<!-- type of differential : SPOOL (locked), FREE, LIMITED SLIP -->
		<attstr name="type" in="NONE,SPOOL,FREE,LIMITED SLIP" val="LIMITED SLIP"/>
	</section>
	
	<section name="Central Differential">
		<attnum name="ratio" min="0" max="10" val="6.85"/>
	</section>
	
	<section name="Front Right Wheel">
		<attnum name="ride height" min="150" max="2000" unit="mm" val="100"/>
		<attnum name="toe" min="-5" max="5" unit="deg" val="0"/>
		<attnum name="camber" min="-5" max="0" unit="deg" val="-5"/>
	</section>
	
	<section name="Front Left Wheel">
		<attnum name="ride height" min="150" max="2000" unit="mm" val="100"/>
		<attnum name="toe" min="-5" max="5" unit="deg" val="0"/>
		<attnum name="camber" min="-5" max="0" unit="deg" val="-5"/>
	</section>
	
	<section name="Rear Right Wheel">
		<attnum name="ride height" min="150" max="2000" unit="mm" val="100"/>
		<attnum name="toe" min="-5" max="5" unit="deg" val="0"/>
		<attnum name="camber" min="-5" max="0" unit="deg" val="-3"/>
	</section>
	
	<section name="Rear Left Wheel">
		<attnum name="ride height" min="150" max="2000" unit="mm" val="100"/>
		<attnum name="toe" min="-5" max="5" unit="deg" val="0"/>
		<attnum name="camber" min="-5" max="0" unit="deg" val="-3"/>
	</section>
	
	<section name="Front Anti-Roll Bar">
		<attnum name="spring" min="0" max="10000" unit="lbs/in" val="0"/>
	</section>
	
	<section name="Rear Anti-Roll Bar">
		<attnum name="spring" min="0" max="10000" unit="lbs/in" val="0"/>
	</section>
	
	<section name="Front Right Suspension">
		<attnum name="spring" min="0" max="10000" unit="lbs/in" val="2000"/>
		<attnum name="suspension course" min="0" max="1.0" unit="m" val="0.30"/>
		<attnum name="bellcrank" min="0.1" max="5" val="1.5"/>
		<attnum name="packers" min="50" max="100" unit="mm" val="0"/>
		<attnum name="slow bump" min="0" max="1000" unit="lbs/in/s" val="200"/>
		<attnum name="slow rebound" min="0" max="1000" unit="lbs/in/s" val="100"/>
		<attnum name="fast bump" min="0" max="1000" unit="lbs/in/s" val="50"/>
		<attnum name="fast rebound" min="0" max="1000" unit="lbs/in/s" val="50"/>
	</section>
	
	<section name="Front Left Suspension">
		<attnum name="spring" min="0" max="10000" unit="lbs/in" val="2000"/>
		<attnum name="suspension course" min="0" max="1.0" unit="m" val="0.30"/>
		<attnum name="bellcrank" min="0.1" max="5" val="1.5"/>
		<attnum name="packers" min="50" max="100" unit="mm" val="0"/>
		<attnum name="slow bump" min="0" max="1000" unit="lbs/in/s" val="200"/>
		<attnum name="slow rebound" min="0" max="1000" unit="lbs/in/s" val="100"/>
		<attnum name="fast bump" min="0" max="1000" unit="lbs/in/s" val="50"/>
		<attnum name="fast rebound" min="0" max="1000" unit="lbs/in/s" val="50"/>
	</section>
	
	<section name="Rear Right Suspension">
		<attnum name="spring" min="0" max="10000" unit="lbs/in" val="2000"/>
		<attnum name="suspension course" min="0" max="1.0" unit="m" val="0.30"/>
		<attnum name="bellcrank" min="0.1" max="5" val="1.5"/>
		<attnum name="packers" min="50" max="100" unit="mm" val="0"/>
		<attnum name="slow bump" min="0" max="1000" unit="lbs/in/s" val="100"/>
		<attnum name="slow rebound" min="0" max="1000" unit="lbs/in/s" val="200"/>
		<attnum name="fast bump" min="0" max="1000" unit="lbs/in/s" val="50"/>
		<attnum name="fast rebound" min="0" max="1000" unit="lbs/in/s" val="50"/>
	</section>
	
	<section name="Rear Left Suspension">
		<attnum name="spring" min="0" max="10000" unit="lbs/in" val="2000"/>
		<attnum name="suspension course" min="0" max="1.0" unit="m" val="0.30"/>
		<attnum name="bellcrank" min="0.1" max="5" val="1.5"/>
		<attnum name="packers" min="50" max="100" unit="mm" val="0"/>
		<attnum name="slow bump" min="0" max="1000" unit="lbs/in/s" val="100"/>
		<attnum name="slow rebound" min="0" max="1000" unit="lbs/in/s" val="200"/>
		<attnum name="fast bump" min="0" max="1000" unit="lbs/in/s" val="50"/>
		<attnum name="fast rebound" min="0" max="1000" unit="lbs/in/s" val="50"/>
	</section>
	
	<section name="Front Right Brake">
		<attnum name="disk diameter" min="100" max="500" unit="mm" val="350"/>
		<attnum name="piston area" min="25" max="200" unit="cm2" val="50"/>
		<attnum name="mu" min="0.25" max="0.5" val="0.45"/>
		<attnum name="inertia" min="0.05" max="0.3" unit="kg.m2" val="0.1241"/>
	</section>
	
	<section name="Front Left Brake">
		<attnum name="disk diameter" min="100" max="500" unit="mm" val="350"/>
		<attnum name="piston area" min="25" max="200" unit="cm2" val="50"/>
		<attnum name="mu" min="0.25" max="0.5" val="0.45"/>
		<attnum name="inertia" min="0.05" max="0.3" unit="kg.m2" val="0.1241"/>
	</section>
	
	<section name="Rear Right Brake">
		<attnum name="disk diameter" min="100" max="500" unit="mm" val="200"/>
		<attnum name="piston area" min="25" max="200" unit="cm2" val="50"/>
		<attnum name="mu" min="0.25" max="0.5" val="0.45"/>
		<attnum name="inertia" min="0.05" max="0.3" unit="kg.m2" val="0.1241"/>
	</section>
	
	<section name="Rear Left Brake">
		<attnum name="disk diameter" min="100" max="500" unit="mm" val="200"/>
		<attnum name="piston area" min="25" max="200" unit="cm2" val="50"/>
		<attnum name="mu" min="0.25" max="0.5" val="0.45"/>
		<attnum name="inertia" min="0.05" max="0.3" unit="kg.m2" val="0.1241"/>
	</section>
	
  <section name="berniw private">
    <attnum name="caero" val="1.0"/>
    <attnum name="cfriction" val="1.10"/>
  </section>

</params>
