=== gerkone/pyTORCS-docker/vtorcs-RL-color/src/libs/tgf/params.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
                          Definitions for params files                                
    file                 : params.dtd
    created              : Fri Aug 13 22:29:02 CEST 1999
    copyright            : (C) 1999 by Eric Espie                         
    email                : torcs@free.fr   
    version              : $Id: params.dtd,v 1.3 2002/11/16 07:20:36 torcs Exp $                                  
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->


<!ELEMENT params (section)+>
<!ATTLIST params
          name CDATA #REQUIRED
	  type CDATA #REQUIRED
	  mode CDATA #IMPLIED
>

<!ELEMENT section (attnum | attstr | section)+>
<!ATTLIST section
          name CDATA #REQUIRED
>

<!ELEMENT attnum EMPTY>
<!ATTLIST attnum 
          name CDATA #REQUIRED
	  min  CDATA #IMPLIED
	  max  CDATA #IMPLIED
	  unit CDATA #IMPLIED
          val  CDATA #REQUIRED
>

<!ELEMENT attstr EMPTY>
<!ATTLIST attstr 
          name CDATA #REQUIRED
	  in   CDATA #IMPLIED
          val  CDATA #REQUIRED
>

=== gerkone/pyTORCS-docker/vtorcs/exp-settings/config/graph.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE params SYSTEM "params.dtd">


<params name="Graph">
  <section name="Graphic">
    <attnum name="smoke value" val="300"/>
    <attnum name="smoke interval" val="0.01"/>
    <attnum name="smoke duration" val="2"/>
    <attnum name="skid value" val="20"/>
    <attnum name="skid length" val="300"/>
    <attnum name="skid interval" val="0.05"/>
    <attnum name="fov factor" val="1"/>
  </section>

  <section name="Playable Cameras Distance of Views">
    <attnum name="Front Level Group Global" val="600"/>
    <attnum name="Front Level Group 1" val="400"/>
    <attnum name="Front Level Group 2" val="300"/>
    <attnum name="Front Level Group 3" val="200"/>
    <attnum name="Rear Level Group Global" val="700"/>
    <attnum name="Rear Level Group 1" val="500"/>
    <attnum name="Rear Level Group 2" val="300"/>
    <attnum name="Rear Level Group 3" val="150"/>
    <attnum name="Front Level Map 1" val="300"/>
    <attnum name="Front Level Map 2" val="200"/>
    <attnum name="Front Level Map 3" val="100"/>
    <attnum name="Rear Level Map 1" val="300"/>
    <attnum name="Rear Level Map 2" val="200"/>
    <attnum name="Rear Level Map 3" val="100"/>
    <attnum name="Level Factor" val="1"/>
    <attnum name="Map Factor" val="1"/>
  </section>

  <section name="UnPlayable Cameras Distance of Views">
    <attnum name="Front Level Group Global" val="400"/>
    <attnum name="Front Level Group 1" val="350"/>
    <attnum name="Front Level Group 2" val="300"/>
    <attnum name="Front Level Group 3" val="200"/>
    <attnum name="Rear Level Group Global" val="400"/>
    <attnum name="Rear Level Group 1" val="350"/>
    <attnum name="Rear Level Group 2" val="300"/>
    <attnum name="Rear Level Group 3" val="200"/>
    <attnum name="Front Level Map 1" val="300"/>
    <attnum name="Front Level Map 2" val="250"/>
    <attnum name="Front Level Map 3" val="200"/>
    <attnum name="Rear Level Map 1" val="300"/>
    <attnum name="Rear Level Map 2" val="250"/>
    <attnum name="Rear Level Map 3" val="200"/>
    <attnum name="Level Factor" val="1"/>
    <attnum name="Map Factor" val="1"/>
  </section>

  <section name="TV Director View">
    <attnum name="change camera interval" val="30"/>
    <attnum name="event interval" val="5"/>
    <attnum name="proximity threshold" val="25"/>
  </section>

  <section name="Display Mode">
    <section name="Player">
      <attnum name="camera" val="0"/>
      <attnum name="camera head list" val="0"/>
    </section>

    <section name="0">
      <attnum name="fovy-9-0" val="9"/>
      <attstr name="current driver" val="berniw 3"/>
      <attnum name="camera" val="4"/>
      <attnum name="camera head list" val="0"/>
      <attnum name="driver board" val="0"/>
      <attnum name="driver counter" val="0"/>
      <attnum name="leader board" val="0"/>
      <attnum name="G graph" val="0"/>
      <attnum name="debug info" val="0"/>
      <attnum name="enable mirror" val="0"/>
      <attnum name="map mode" val="1"/>
      <attnum name="fovy-0-4" val="67.5"/>
    </section>

  </section>

  <section name="OpenGL Features">
    <attstr name="texture compression ARB" val="disabled"/>
    <attnum name="user texture sizelimit" val="128"/>
  </section>

</params>

=== gerkone/pyTORCS-docker/vtorcs-RL-color/src/drivers/berniw3/6/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    file        : kc-corvette-ttop.xml
    created     : Sat Aug 30 20:25:50 CEST 2003
    copyright   : (C) 2003 by Eric Espié
    email       : Eric.Espie@torcs.org
    version     : $Id: default.xml,v 1.1 2004/01/20 13:45:23 berniw Exp $
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!DOCTYPE params SYSTEM "../../../../src/libs/tgf/params.dtd">

<!-- 3D Model copyright by Butch (K/cendra) (see readme.txt) -->

<params name="Corvette T-Top" type="template" mode="mw">

  <section name="Gearbox">
    <section name="gears">
      <section name="r">
        <attnum name="ratio" val="-2.9"/>
      </section>
      <section name="1">
        <attnum name="ratio" val="4.91098"/>
      </section>
      <section name="2">
        <attnum name="ratio" val="2.8"/>
      </section>
      <section name="3">
        <attnum name="ratio" val="1.7529"/>
      </section>
      <section name="4">
        <attnum name="ratio" val="1.05"/>
      </section>
    </section>
  </section>

  <section name="Brake System">
    <attnum name="front-rear brake repartition" min=".3" max=".7" val="0.7"/>
    <attnum name="max pressure" min="100" max="1.5e+06" unit="kPa" val="35000"/>
  </section>

  <section name="Rear Differential">
    <attstr name="type" val="LIMITED SLIP"/>
    <attnum name="ratio" val="3.55"/>
  </section>

  <section name="Front Right Wheel">
    <attnum name="ride height" min="100" max="2000" unit="mm" val="150"/>
    <attnum name="toe" min="-5" max="5" unit="deg" val="0"/>
    <attnum name="camber" min="-5" max="0" unit="deg" val="0"/>
  </section>

  <section name="Front Left Wheel">
    <attnum name="ride height" min="50" max="2000" unit="mm" val="150"/>
    <attnum name="toe" min="-5" max="5" unit="deg" val="0"/>
    <attnum name="camber" min="-5" max="0" unit="deg" val="0"/>
  </section>

  <section name="Rear Right Wheel">
    <attnum name="ride height" min="50" max="2000" unit="mm" val="150"/>
    <attnum name="toe" min="-5" max="5" unit="deg" val="0"/>
    <attnum name="camber" min="-5" max="0" unit="deg" val="0"/>
  </section>

  <section name="Rear Left Wheel">
    <attnum name="ride height" min="50" max="2000" unit="mm" val="150"/>
    <attnum name="toe" min="-5" max="5" unit="deg" val="0"/>
    <attnum name="camber" min="-5" max="0" unit="deg" val="0"/>
  </section>

  <section name="Front Anti-Roll Bar">
    <attnum name="spring" min="0" max="10000" unit="lbs/in" val="10"/>
    <attnum name="suspension course" min="0" max="1" unit="m" val="0.2"/>
    <attnum name="bellcrank" min="0.5" max="5" val="2.5"/>
  </section>

  <section name="Rear Anti-Roll Bar">
    <attnum name="spring" min="0" max="10000" unit="lbs/in" val="10"/>
    <attnum name="suspension course" min="0" max="1" unit="m" val="0.2"/>
    <attnum name="bellcrank" min="0.5" max="5" val="2.5"/>
  </section>

  <section name="Front Right Suspension">
    <attnum name="spring" min="0" max="10000" unit="lbs/in" val="2500"/>
    <attnum name="suspension course" min="0" max="1" unit="m" val="0.25"/>
    <attnum name="packers" unit="mm" min="0" max="100" val="50"/>
    <attnum name="bellcrank" min="0.1" max="5" val="1"/>
    <attnum name="slow bump" min="0" max="1000" unit="lbs/in/s" val="200"/>
    <attnum name="slow rebound" min="0" max="1000" unit="lbs/in/s" val="200"/>
    <attnum name="fast bump" min="0" max="1000" unit="lbs/in/s" val="100"/>
    <attnum name="fast rebound" min="0" max="1000" unit="lbs/in/s" val="100"/>
  </section>

  <section name="Front Left Suspension">
    <attnum name="spring" min="0" max="10000" unit="lbs/in" val="2500"/>
    <attnum name="suspension course" min="0" max="1" unit="m" val="0.25"/>
    <attnum name="packers" unit="mm" min="0" max="100" val="50"/>
    <attnum name="bellcrank" min="0.1" max="5" val="1"/>
    <attnum name="slow bump" min="0" max="1000" unit="lbs/in/s" val="200"/>
    <attnum name="slow rebound" min="0" max="1000" unit="lbs/in/s" val="200"/>
    <attnum name="fast bump" min="0" max="1000" unit="lbs/in/s" val="100"/>
    <attnum name="fast rebound" min="0" max="1000" unit="lbs/in/s" val="100"/>
  </section>

  <section name="Rear Right Suspension">
    <attnum name="spring" min="0" max="10000" unit="lbs/in" val="2500"/>
    <attnum name="suspension course" min="0" max="1" unit="m" val="0.25"/>
    <attnum name="packers" unit="mm" min="0" max="100" val="50"/>
    <attnum name="bellcrank" min="0.1" max="5" val="1"/>
    <attnum name="slow bump" min="0" max="1000" unit="lbs/in/s" val="200"/>
    <attnum name="slow rebound" min="0" max="1000" unit="lbs/in/s" val="200"/>
    <attnum name="fast bump" min="0" max="1000" unit="lbs/in/s" val="100"/>
    <attnum name="fast rebound" min="0" max="1000" unit="lbs/in/s" val="100"/>
  </section>

  <section name="Rear Left Suspension">
    <attnum name="spring" min="0" max="10000" unit="lbs/in" val="2500"/>
    <attnum name="suspension course" min="0" max="1" unit="m" val="0.25"/>
    <attnum name="packers" unit="mm" min="0" max="100" val="50"/>
    <attnum name="bellcrank" min="0.1" max="5" val="1"/>
    <attnum name="slow bump" min="0" max="1000" unit="lbs/in/s" val="200"/>
    <attnum name="slow rebound" min="0" max="1000" unit="lbs/in/s" val="200"/>
    <attnum name="fast bump" min="0" max="1000" unit="lbs/in/s" val="100"/>
    <attnum name="fast rebound" min="0" max="1000" unit="lbs/in/s" val="100"/>
  </section>

  <section name="berniw private">
    <attnum name="caero" val="0.9"/>
    <attnum name="cfriction" val="0.8"/>
  </section>

</params>

=== gerkone/pyTORCS-docker/torcs/src/drivers/sparkle/sparkle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    file                 : sparkle.xml
    created              : Wed Jan 8 18:31:16 CET 2003
    copyright            : (C) 2002 Bernhard Wymann
    email                : berniw@bluewin.ch
    version              : $Id: sparkle.xml,v 1.2 2003/08/13 00:03:15 berniw Exp $
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->

<!DOCTYPE params SYSTEM "../../libs/tgf/params.dtd">

<params name="sparkle" type="robotdef">
  <section name="Robots">
    <section name="index">

      <section name="0">
        <attstr name="name" val="sparkle 1"></attstr>
        <attstr name="desc" val=""></attstr>
        <attstr name="team" val="sparkle"></attstr>
        <attstr name="author" val="Eva Tscheulin"></attstr>
        <attstr name="car name" val="baja-bug"></attstr>
        <attnum name="race number" val="81"></attnum>
        <attnum name="red" val="1.0"></attnum>
        <attnum name="green" val="0.0"></attnum>
        <attnum name="blue" val="1.0"></attnum>
      </section>

    </section>
  </section>
</params>

=== gerkone/pyTORCS-docker/vtorcs/src/drivers/olethros/5/default.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
    file                 : car4-trb1.xml
    created              : Thu Oct 11 13:15:57 CET 2007
    copyright            : (C) 2007 by Eric EspiÃ©, Bernhard Wymann
    email                : berniw@bluewin.ch
    version              : $Id: default.xml,v 1.5.2.1 2008/05/30 23:18:14 berniw Exp $
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->
<!DOCTYPE params SYSTEM "../../../../src/libs/tgf/params.dtd">

<params name="car4-trb1" type="template">

  <section name="Car">
    <attnum name="initial fuel" unit="l" min="1.0" max="95.0" val="95.0"/>
  </section>

  <section name="Front Wing">
	  <attnum name="angle" unit="deg" min="0" max="12" val="4"/>
  </section>

  <section name="Rear Wing">
    <attnum name="angle" unit="deg" min="0" max="18" val="10"/>
  </section>

  <section name="Gearbox">
    <section name="gears">
      <section name="r">
        <attnum name="ratio" min="-3" max="0" val="-2.0"/>
      </section>

      <section name="1">
        <attnum name="ratio" min="0" max="5" val="3.8"/>
      </section>

      <section name="2">
        <attnum name="ratio" min="0" max="5" val="2.8"/>
      </section>

      <section name="3">
        <attnum name="ratio" min="0" max="5" val="1.85"/>
      </section>

      <section name="4">
        <attnum name="ratio" min="0" max="5" val="1.45"/>
      </section>

      <section name="5">
        <attnum name="ratio" min="0" max="5" val="1.25"/>
      </section>

      <section name="6">
        <attnum name="ratio" min="0" max="5" val="1.08"/>
      </section>
    </section>
  </section>

  <section name="Brake System">
    <attnum name="front-rear brake repartition" min="0.3" max="0.7" val="0.52"/>
    <attnum name="max pressure" unit="kPa" min="100" max="150000" val="30000"/>
  </section>

  <section name="Rear Differential">
    <attstr name="type" in="SPOOL,FREE, LIMITED SLIP" val="LIMITED SLIP"/>
    <attnum name="ratio" min="0" max="10" val="3.07"/>
  </section>

  <section name="Front Right Wheel">
    <attnum name="ride height" unit="mm" min="100" max="300" val="100"/>
    <attnum name="toe" unit="deg" min="-5" max="5" val="0"/>
    <attnum name="camber" min="-5" max="-3" unit="deg" val="-5"/>
  </section>

  <section name="Front Left Wheel">
    <attnum name="ride height" unit="mm" min="100" max="300" val="100"/>
    <attnum name="toe" unit="deg" min="-5" max="5" val="0"/>
    <attnum name="camber" min="-5" max="-3" unit="deg" val="-5"/>
  </section>

  <section name="Rear Right Wheel">
    <attnum name="ride height" unit="mm" min="100" max="300" val="100"/>
    <attnum name="toe" unit="deg" min="0" max="0" val="0"/>
    <attnum name="camber" min="-5" max="-2" unit="deg" val="-3"/>
  </section>

  <section name="Rear Left Wheel">
    <attnum name="ride height" unit="mm" min="100" max="300" val="100"/>
    <attnum name="toe" unit="deg" min="0" max="0" val="0"/>
    <attnum name="camber" min="-5" max="-2" unit="deg" val="-3"/>
  </section>

  <section name="Front Anti-Roll Bar">
    <attnum name="spring" unit="lbs/in" min="0" max="5000" val="0"/>
  </section>

  <section name="Rear Anti-Roll Bar">
    <attnum name="spring" unit="lbs/in" min="0" max="5000" val="0"/>
  </section>

  <section name="Front Right Suspension">
    <attnum name="spring" unit="lbs/in" min="0" max="10000" val="5500"/>
    <attnum name="suspension course" unit="m" min="0" max="0.2" val="0.07"/>
    <attnum name="bellcrank" min="0.1" max="5" val="0.9"/>
    <attnum name="packers" unit="mm" min="0" max="10" val="10"/>
    <attnum name="slow bump" unit="lbs/in/s" min="0" max="1000" val="500"/>
    <attnum name="slow rebound" unit="lbs/in/s" min="0" max="1000" val="300"/>
    <attnum name="fast bump" unit="lbs/in/s" min="0" max="1000" val="80"/>
    <attnum name="fast rebound" unit="lbs/in/s" min="0" max="1000" val="80"/>
  </section>

  <section name="Front Left Suspension">
    <attnum name="spring" unit="lbs/in" min="0" max="10000" val="5500"/>
    <attnum name="suspension course" unit="m" min="0" max="0.2" val="0.07"/>
    <attnum name="bellcrank" min="0.1" max="5" val="0.9"/>
    <attnum name="packers" unit="mm" min="0" max="10" val="10"/>
    <attnum name="slow bump" unit="lbs/in/s" min="0" max="1000" val="500"/>
    <attnum name="slow rebound" unit="lbs/in/s" min="0" max="1000" val="300"/>
    <attnum name="fast bump" unit="lbs/in/s" min="0" max="1000" val="80"/>
    <attnum name="fast rebound" unit="lbs/in/s" min="0" max="1000" val="80"/>
  </section>

  <section name="Rear Right Suspension">
    <attnum name="spring" unit="lbs/in" min="0" max="10000" val="5500"/>
    <attnum name="suspension course" unit="m" min="0" max="0.2" val="0.13"/>
    <attnum name="bellcrank" min="0.1" max="5" val="1.1"/>
    <attnum name="packers" unit="mm" min="0" max="10" val="10"/>
    <attnum name="slow bump" unit="lbs/in/s" min="0" max="1000" val="400"/>
    <attnum name="slow rebound" unit="lbs/in/s" min="0" max="1000" val="500"/>
    <attnum name="fast bump" unit="lbs/in/s" min="0" max="1000" val="80"/>
    <attnum name="fast rebound" unit="lbs/in/s" min="0" max="1000" val="80"/>
  </section>

  <section name="Rear Left Suspension">
    <attnum name="spring" unit="lbs/in" min="0" max="10000" val="5500"/>
    <attnum name="suspension course" unit="m" min="0" max="0.2" val="0.13"/>
    <attnum name="bellcrank" min="0.1" max="5" val="1.1"/>
    <attnum name="packers" unit="mm" min="0" max="10" val="10"/>
    <attnum name="slow bump" unit="lbs/in/s" min="0" max="1000" val="400"/>
    <attnum name="slow rebound" unit="lbs/in/s" min="0" max="1000" val="500"/>
    <attnum name="fast bump" unit="lbs/in/s" min="0" max="1000" val="80"/>
    <attnum name="fast rebound" unit="lbs/in/s" min="0" max="1000" val="80"/>
  </section>

  <section name="Front Right Brake">
    <attnum name="disk diameter" unit="mm" min="100" max="380" val="380"/>
    <attnum name="piston area" unit="cm2" val="50"/>
    <attnum name="mu" val="0.45"/>
    <attnum name="inertia" unit="kg.m2" val="0.1241"/>
  </section>

  <section name="Front Left Brake">
    <attnum name="disk diameter" unit="mm" min="100" max="380" val="380"/>
    <attnum name="piston area" unit="cm2" val="50"/>
    <attnum name="mu" val="0.45"/>
    <attnum name="inertia" unit="kg.m2" val="0.1241"/>
  </section>

  <section name="Rear Right Brake">
    <attnum name="disk diameter" unit="mm" min="100" max="380" val="330"/>
    <attnum name="piston area" unit="cm2" val="25"/>
    <attnum name="mu" val="0.45"/>
    <attnum name="inertia" unit="kg.m2" val="0.0714"/>
  </section>

  <section name="Rear Left Brake">
    <attnum name="disk diameter" unit="mm" min="100" max="380" val="330"/>
    <attnum name="piston area" unit="cm2" val="25"/>
    <attnum name="mu" val="0.45"/>
    <attnum name="inertia" unit="kg.m2" val="0.0714"/>
  </section>
</params>

=== gerkone/pyTORCS-docker/vtorcs-RL-color/data/tracks/e-track-5/e-track-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    file                 : e-track-5.xml
    created              : Sun Apr 30 15:45:57 CEST 2000
    copyright            : (C) 2000 by Eric Espie                         
    email                : torcs@free.fr   
    version              : $Id: e-track-5.xml,v 1.7 2004/02/09 05:42:42 torcs Exp $                                  
-->

<!--    This program is free software; you can redistribute it and/or modify  -->
<!--    it under the terms of the GNU General Public License as published by  -->
<!--    the Free Software Foundation; either version 2 of the License, or     -->
<!--    (at your option) any later version.                                   -->


<!DOCTYPE params SYSTEM "../../../src/libs/tgf/params.dtd" [
<!-- general definitions for tracks -->
<!ENTITY default-surfaces SYSTEM "../../../data/tracks/surfaces.xml">
]>

<params name="e-track-5" type="template" mode="mw">

  <section name="Surfaces">
    <section name="List">
      &default-surfaces;
    </section>
  </section>

  <section name="Header">
    <attstr name="name"        val="E-Track 5"/>
    <attstr name="category"    val="oval"/>
    <attnum name="version"     val="3"/>
    <attstr name="author"      val="E.Espie"/>
    <attstr name="description" val=""/>
  </section>

  <section name="Graphic">
    <attstr name="3d description" val="e-track-5.ac"/>
    <attstr name="background image" val="background.png"/>
    <attnum name="background type" val="2"/>
    <attnum name="background color R" val="0.28125"/>
    <attnum name="background color G" val="0.4375"/>
    <attnum name="background color B" val="0.75"/>

    <attnum name="ambient color R" val="0.1"/>
    <attnum name="ambient color G" val="0.1"/>
    <attnum name="ambient color B" val="0.05"/>

    <attnum name="diffuse color R" val="1"/>
    <attnum name="diffuse color G" val="1"/>
    <attnum name="diffuse color B" val="1"/>

    <attnum name="specular color R" val="0.1"/>
    <attnum name="specular color G" val="0.1"/>
    <attnum name="specular color B" val="0.1"/>


    <attnum name="light position x" val="-0"/>
    <attnum name="light position y" val="1000"/>
    <attnum name="light position z" val="300"/>


    <section name="Environment Mapping">
      <section name="1">
	<attstr name="env map image" val="env.png"/>
      </section>
    </section>

    <section name="Terrain Generation">
      <attnum name="track step" unit="m" val="30"/>
      <attnum name="border margin" unit="m" val="100"/>
      <attnum name="border step" unit="m" val="30"/>
      <attnum name="border height" unit="m" val="20"/>
      <attstr name="orientation" val="anti-clockwise"/>
    </section>
  </section>



  <section name="Main Track">

    <attnum name="width" unit="m" val="20"/>
    <attstr name="surface" in="asphalt,concrete,grass,sand,dirt" val="asphalt-lines"/>
    <attnum name="rside width" val="4"/>
    <attstr name="rside surface"  val="grass"/>
    <attstr name="rside type" in="level,tangent" val="level"/>
    <attnum name="lside width" val="4"/>
    <attstr name="lside surface"  val="grass"/>
    <attstr name="lside type" in="level,tangent" val="level"/>

    <attnum name="profil steps length" val="5" unit="m"/>

    <section name="segments">

      <section name="s1">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="100"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="0" unit="deg"/>
 	<attnum name="z end" unit="m" val="0"/>
      </section>

      <section name="t1-1">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="66.25"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="-5" unit="deg"/>
 	<attnum name="z end" unit="m" val="-1"/>
	<attstr name="surface" val="asphalt-l-left"/>
      </section>

      <section name="t1-2">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="66.25"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="0" unit="deg"/>
 	<attnum name="z end" unit="m" val="0"/>
	<attstr name="surface" val="asphalt-l-left"/>
      </section>

      <section name="t2-1">
        <attstr name="type" val="rgt"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="42.5"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="10" unit="deg"/>
 	<attnum name="z end" unit="m" val="-0.5"/>
	<attstr name="surface" val="asphalt-l-right"/>
      </section>

      <section name="t2-2">
        <attstr name="type" val="rgt"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="42.5"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="0" unit="deg"/>
 	<attnum name="z end" unit="m" val="0"/>
	<attstr name="surface" val="asphalt-l-right"/>
      </section>

      <section name="t3-1">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="66.25"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="-5" unit="deg"/>
 	<attnum name="z end" unit="m" val="-1"/>
	<attstr name="surface" val="asphalt-l-left"/>
      </section>

      <section name="t3-2">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="66.25"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="0" unit="deg"/>
 	<attnum name="z end" unit="m" val="0"/>
	<attstr name="surface" val="asphalt-l-left"/>
      </section>

      <section name="s2">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="200"/>
	<attstr name="surface" val="asphalt-lines"/>
      </section>

      <section name="t4-1">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="66.25"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="-5" unit="deg"/>
 	<attnum name="z end" unit="m" val="-1"/>
	<attstr name="surface" val="asphalt-l-left"/>
      </section>

      <section name="t4-2">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="66.25"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="0" unit="deg"/>
 	<attnum name="z end" unit="m" val="0"/>
	<attstr name="surface" val="asphalt-l-left"/>
      </section>

      <section name="t5-1">
        <attstr name="type" val="rgt"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="42.5"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="10" unit="deg"/>
 	<attnum name="z end" unit="m" val="-0.5"/>
	<attstr name="surface" val="asphalt-l-right"/>
      </section>

      <section name="t5-2">
        <attstr name="type" val="rgt"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="42.5"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="0" unit="deg"/>
 	<attnum name="z end" unit="m" val="0"/>
	<attstr name="surface" val="asphalt-l-right"/>
      </section>

      <section name="t6-1">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="66.25"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="-5" unit="deg"/>
 	<attnum name="z end" unit="m" val="-1"/>
	<attstr name="surface" val="asphalt-l-left"/>
      </section>

      <section name="t6-2">
        <attstr name="type" val="lft"/>
	<attnum name="radius" unit="m" val="100"/>
	<attnum name="arc" unit="deg" val="66.25"/>
	<attstr name="profil" in="linear,spline" val="spline"/>
 	<attnum name="banking end" val="0" unit="deg"/>
 	<attnum name="z end" unit="m" val="0"/>
	<attstr name="surface" val="asphalt-l-left"/>
      </section>

      <section name="s3">
        <attstr name="type" val="str"/>
	<attnum name="lg" unit="m" val="100"/>
	<attstr name="surface" val="asphalt-lines"/>
      </section>


    </section>

  </section>

</params>
